TABLE_NAME = "Watermark_Control"

# ── Load Modes ──
MODE_INCREMENTAL = "INCREMENTAL"
MODE_FULL_RELOAD = "FULL_RELOAD"
MODE_SKIP        = "SKIP"

VALID_MODES = frozenset({MODE_INCREMENTAL, MODE_FULL_RELOAD, MODE_SKIP})

# ── Column Names ──
# 1. Identity
COL_SOURCE       = "SOURCE"
COL_TABLE_NAME   = "TABLE_NAME"
COL_AREA         = "AREA"
COL_IS_DIMENSION = "IS_DIMENSION"

# 2. Routing
COL_SILVER_TABLE = "SILVER_TABLE"
COL_BRONZE_PATH  = "BRONZE_PATH"

# 3. Extraction & Merge
COL_SOURCE_QUERY      = "SOURCE_QUERY"
COL_SOURCE_DATECOL    = "SOURCE_DATECOL"
COL_SOURCE_DATECOL_FORMAT = "SOURCE_DATECOL_FORMAT"
COL_WINDOW_DAYS       = "WINDOW_DAYS"
COL_PK_COLUMNS     = "PK_COLUMNS"

# 4. Control
COL_ACTIVE        = "ACTIVE"
COL_LOAD_MODE     = "LOAD_MODE"
COL_NEXT_RUN_MODE = "NEXT_RUN_MODE"
COL_RUN_ORDER     = "RUN_ORDER"

# 5. State & Audit
COL_WATERMARK_LAST = "WATERMARK_LAST_VALUE"
COL_LAST_RUN_AT    = "LAST_RUN_AT"
COL_LAST_RUN_OK    = "LAST_RUN_OK"
COL_LAST_ERROR     = "LAST_ERROR"
COL_CREATED_AT     = "CREATED_AT"
COL_UPDATED_AT     = "UPDATED_AT"
